# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfaairquality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor1data',
            name='data_int',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor1data',
            name='data_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor2data',
            name='data_int',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor2data',
            name='data_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor3data',
            name='data_int',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor3data',
            name='data_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor4data',
            name='data_int',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensor4data',
            name='data_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
