# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfaairquality', '0002_auto_20170429_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordetails',
            name='sensor_data_interval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
