# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfaairquality', '0003_sensordetails_sensor_data_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordetails',
            name='sensor_created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sensordetails',
            name='sensor_data_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sensordetails',
            name='sensor_modified_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
