# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfaairquality', '0004_auto_20170429_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordetails',
            name='sensor_created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensordetails',
            name='sensor_modified_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
